# ????
spring.application.name=hello_server
server.port=8081

# MySQL ?????
spring.datasource.url=jdbc:mysql://localhost:3382/spring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Redis ?????
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# MyBatis-Plus ??
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.global-config.db-config.id-type=auto

# JWT??
security.jwt.secret=MySecretKeyForJWTGeneration2024SpringBootDemoApplication
security.jwt.expiration-millis=7200000